version: '2'
services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql:latest #consider to use mariadb ref. https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql#comment69940546_39208187
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'some_user'
      MYSQL_PASS: 'some_user'
    volumes:
      - my-datavolume:/var/lib/mysql #the volume to be created at @physical-machine:/var/lib/docker/volumes
    ports:
      - '33066:3306' #local-port:container-port
volumes:
  my-datavolume:

